config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    resources :courses do
    collection do
      get 'search'
    end
   end
   root 'courses#index'
    
    match '/about_us',   to: 'pages#about_us', via: :get
    match '/contact_us', to: 'pages#contact_us', via: :get
  

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
    
    belongs_to :user
    
end

app/models/course.rb
class Course < ActiveRecord::Base
    
   has_many :users
   
   validates_presence_of :name
   validates_presence_of :coursecode
   validates_presence_of :description
   
   def self.search(params)
       courses = courses.where("name like? or description like?", "%#{params[:search]}") if params[:search].present?
   end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :course
         
  enum role: {student: 0, teacher: 1, admin: 2}
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :student
  end
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
    before_action :add_parameters_to_user, if: :devise_controller?
  
  def add_parameters_to_user
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username]) 
   devise_parameter_sanitizer.permit(:account_update, keys: [:username])
   
  end
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    
    def new
        
    end
    
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController 
   
   def index
   end
   
   def new
       @course = Course.new
   end
   
   def show
       @course = Course.find(params[:id])
   end
   
   def create
        @course = Course.new(course_params)
        if @course.save
            redirect_to @course
        else
            flash[:danger] = @course.errors.full_messages.to_sentence
            render 'new'
        end
   end
   
   def search
        @courses = Course.search(params)
        
   end
    
     private
        def course_params
            params.require(:course).permit(:name, :description, :coursecode)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   
   def about_us
       
   end
   
   def contact_us
       
   end
   
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<div id="home-search-container">
<div class="container">
    <div class="row">
        <div class="span12">
            <div class="widget pull-right">
                
                <div class="container" style="padding-bottom: 50px; padding-top: 50px;">
                            <h2 class="head-title">Welcome to ClassCheck</h2>
                            <p class="head-message"><strong>ClassCheck is the best solution to keep track of course requirements.</strong><br />
                           
                            <%= link_to "Create a Course", new_course_path, class: "btn-custom" %> 
</div>
          
       
    </div>
    </div>
    </div>
    </div>
    <section>
      <div class="container" style="padding-bottom: 50px; padding-top: 100px;">
         <div class="search-form">
             <p><strong>Search for Courses</strong></p>
             <%= form_tag search_courses_path, method: :get do |f| %>
                 <%= text_field_tag :search , nil, placeholder: "ENSC, CMPT, MATH, ENGL,..."%>
                 <%= text_field_tag :coursecode , nil, placeholder: " "%> <br />
                 <%= submit_tag  'Find your Course', class: "btn span3 btn-realto-form btn-large" %>
             <% end %>
         </div>
         </section>
    
    <!-- .span8  -->

    <!-- .span4  -->
</div>
</div>
</div>
</div>

app/views/courses/new.html.erb
<center><div class="container page-content">
    <div class="row">
        <div class="span8">
           
                <div class="padding30">
                    <h2 class="page-title">Create a Course</h2>
                    
                    <%= form_for @course do |f| %>
                    <%= f.label :name %>
                    <%= f.text_field :name %>
                    <%= f.label :coursecode %>
                    <%= f.text_field :coursecode %>
                    <%= f.label :description %>
                    <%= f.text_area :description %><br />
                    
                    <%= f.submit class: "btn span3 btn-realto-form btn-large" %>
                    
                    <% end %>
                    
                    
                    </div>
         
        </div>
    </div>
</div>
</center>

app/views/courses/search.html.erb
<div class="container page-content">
    <div class="row">
        <div class="span12">
            <div class="row">
                <% if @courses.blank? %>
              >
                <h3><bold>Could not find a course with your search criteria</bold></h3>
                
                <% else %>
                <% @courses.each do |course| %>
                <div class="span4 box-container">
                    <div class="holder">
                        <a class="overlay" href="#" title="property title">
                            <span class="more"></span>
                            <% if course.image_url.present? %>
                                <%= link_to image_tag(course.image_url.to_s), course %>
                            <% else %>
                                <%= link_to image_tag("https://placehold.it/370x210"), course %>
                             <% end %>
                        </a>
                        
                        <div class="prop-info">
                            <h3 class="prop-title"><%= link_to course.name, course %></h3>
                            <ul class="more-info clearfix">
                                <li class="info-label clearfix"><span class="pull-left">Course Code:</span>
                                    <span class="qty pull-right"><%= course.coursecode %></span></li>
                                <li class="info-label clearfix"><span class="pull-left">Description: </span>
                                    <span class="qty pull-right"><%= course.description %></span></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <% end %>
                <% end %>
                    </div>
                </div>
                <!-- .span4 .box-container -->
            </div>
            <!-- .row -->
        </div>
        <!-- .span12 -->
    </div>
    <!-- .row -->
</div>

app/views/courses/show.html.erb
 <div class="clearfix padding030 row-fluid">
     <h1 class="info-label clearfix"><span class="pull-left">Course Name:</span>
                                <span class="qty pull-left"><%= @course.name %></span></h1>
                        <ul class="more-info pull-left span6">
                            
                            <li class="info-label clearfix"><span class="pull-left">Description:</span>
                                <span class="qty pull-right"><%= @course.description %></span></li>
                         
                        </ul>
                    </div>
                    <div class="clearfix padding030 row-fluid">
                    <center><%= link_to "Take Attendance", new_user_session_path, class: "btn span3 btn-realto-form btn-large" %> </center>
                    </div>
                    

app/views/layouts/_footer.html.erb
<!-- begin footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="span3">
                        <div class="footer-widget">
                            <h2 class="brand widget-title">ClassCHeck</h2>
                            <p class="footer-tag-line">Perfecting Participation</p>
                            <p>Keep track of your courses</p>
                        </div>
                        <!-- .footer-company-info -->
                    </div>
                    <!-- .span3 -->
                    <div class="span3">
                        <div class="footer-widget">
                            <h3 class="widget-title">Address</h3>
                            <div class="clearfix">
                                <ul>
                                    <li class="clearfix">
                                        <i class="icon-map-marker pull-left"></i>
                                        <p class="pull-left">Burnaby, BC
                                            <br />Canada</p></li>
                                    <li class="clearfix">
                                        <i class="icon-phone pull-left"></i>
                                        <p class="pull-left">phone number</p></li>
                                    <li class="clearfix">
                                        <i class="icon-envelope-alt pull-left"></i>
                                        <p class="pull-left"><a href="#">willmakeemail@gmail.com</a></p>
                                    </li>
                                </ul>
                            </div>
                            <!-- .clearfix -->
                        </div>
                        <!-- .footer-widget -->
                    </div>
                    <!-- .span3 -->
                    <div class="span3">
                        <div class="footer-widget">
                            <h3 class="widget-title">Company</h3>
                            <ul>
                                <li>
                                    <i class="icon-caret-right"></i>
                                    <a title="Home" href="#">Home</a></li>
                                <li>
                                    <i class="icon-caret-right"></i>
                                    <a title="About Us" href="#">About Us</a></li>
                                <li>
                                 
                                <li>
                                    <i class="icon-caret-right"></i>
                                    <a title="Contact Us" href="#">Contact Us</a></li>
                            </ul>
                        </div>
                        <!-- .footer-widget -->
                    </div>
    
                </div>
            </div>
        </footer>
         
        <!-- end footer -->

app/views/layouts/_header.html.erb
<!-- begin header -->
        <header>
            <div class="navbar navbar-inverse navbar-static-top">
                <div class="navbar-inner">
                    <div class="container">
                        <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="nav-collapse collapse">
                            <ul class="nav">
                                
                                <li>
                                    <%= link_to root_path do %>
                                    <i class="icon-home"></i>
                                    <% end %>
                                </li> 
                                
                                </li>
                                <li><%= link_to "About Us", about_us_path %></li>
                                <li><%= link_to "Contact Us", contact_us_path %></li>
                             </ul>
                        
                        </div>
                        <!--/.nav-collapse -->
                    </div>
                </div>
            </div>
            <div id="logo-container">
                <div class="container">
                    <div class="row">
                        <div class="span8">
                            <span class="logo-text"><%= link_to "ClassCheck", root_path, class: "brand" %></span>
                            <span class="tag-line hidden-phone">Perfecting Participation</span>
                        </div>
                        <div class="span4">
                            <ul class="inline pull-right">
                               <% if user_signed_in? %>
                               <%= link_to "Edit Account", edit_user_registration_path, class: "btn-custom" %>
                               <%= link_to "Sign Out", destroy_user_session_path, class: "btn-custom", method: :delete %>
                               
                               <% else %>
                                <%= link_to "Sign In", new_user_session_path, class: "btn-custom" %>
                                <%= link_to "Register", new_user_registration_path, class: "btn-custom" %> 
                               <% end %>
                            </ul>
                         
                        </div>
                    </div>
                </div>
            </div>
            <!-- #logo-container -->
        </header>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %> 
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>